name: GO CI
on:
  pull_request:

    types: [opened, synchronize, reopened]

    branches: dev
jobs:
  go_test:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.ref == 'go-backend'

    steps:
      - name: setup go
        uses: actions/setup-go@v5.1.0
        with:
          go-verions: '1.23.1'
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: go-backend
      - name: install dependencies
        working-directory: ./auth-service
        run: go mod download
      - name: run test
        working-directory: ./auth-service/tests
        run: go test
          
