name: Integration tests
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  integration_test:
    runs-on: self-hosted
    steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: setup go
      uses: actions/setup-go@v5.1.0
      with:
        go-version: '1.23.1'
    - name: setup python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'
    - name: checkout
      uses: actions/checkout@v4.2.2
      with:
        ref: dev
    - name: run python server
      working-directory: ./hackathon-backend
      run: uvicorn editor.app:app --host 0.0.0.0 --port 8001 --reload"
    - name: run go server
      working-directory: ./auth-service
      run: go run .
    - name: test
      working-directory: ./frontend/integration-tests
      run: npm run integration-tests
