name: Python CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: dev
jobs:
  python_test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.ref == 'python-backend'
    steps:
      - name: setup python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11'
      - name: checkout
        uses: actions/checkout@v4.2.2
        with: 
          ref: python-backend
      - name: install dependencies
        working-directory: ./hackathon_backend
        run: pip install --no-cache-dir -r requirements.txt
      - name: run tests
        working-directory: ./hackathon_backend/tests/tests_utils
        run: python -m unittest discover
